feat(homebrew): split packages into bootstrap and manual groups

diff --git a/home/dot_local/bin/executable_install-heavy-packages.tmpl b/home/dot_local/bin/executable_install-heavy-packages.tmpl
--- a/home/dot_local/bin/executable_install-heavy-packages.tmpl
+++ b/home/dot_local/bin/executable_install-heavy-packages.tmpl
@@ -1,12 +1,18 @@
 #!/bin/sh
 
 # chezmoi:template:left-delimiter=#{ right-delimiter=}#
-# packages.yaml hash: #{ include ".chezmoidata/packages.yaml" | sha256sum }#
 
-#{ if eq .chezmoi.os "darwin" }#
+# Install heavy Homebrew packages on demand.
+
+if ! command -v brew >/dev/null 2>&1; then
+    echo "Error: Homebrew is not installed." >&2
+    exit 1
+fi
+
+#{ if eq .chezmoi.os "darwin" -}#
 brew bundle --file=/dev/stdin <<EOF
 
-#{- range .packages.darwin.bootstrap.formulae -}#
+#{- range .packages.darwin.manual.formulae -}#
   #{- if eq "map" (kindOf .) }#
     tap #{ .tap | quote }#
     brew #{ .name | quote }#
@@ -15,7 +21,7 @@ brew bundle --file=/dev/stdin <<EOF
   #{- end }#
 #{- end }#
 
-#{- range .packages.darwin.bootstrap.casks -}#
+#{- range .packages.darwin.manual.casks -}#
   #{- if eq "map" (kindOf .) }#
     tap #{ .tap | quote }#
     cask #{ .name | quote }#
@@ -28,18 +34,9 @@ EOF
 #{- end }#
 
 #{ if eq .chezmoi.os "linux" -}#
-sudo apt-get update
-sudo apt-get install --yes #{ .packages.linux.apts | join " " }#
-
-if [ -f /.dockerenv ]; then
-    # We are in Ubuntu Docker container in macOS, brew is not working properly there
-    # so we are just exiting
-    exit
-fi
-
 brew bundle --file=/dev/stdin <<EOF
 
-#{- range .packages.linux.bootstrap.formulae -}#
+#{- range .packages.linux.manual.formulae -}#
   #{- if eq "map" (kindOf .) }#
     tap #{ .tap | quote }#
     brew #{ .name | quote }#
@@ -49,5 +46,4 @@ brew bundle --file=/dev/stdin <<EOF
 #{- end }#
 
 EOF
-
-#{ end -}#
+#{- end }#
